version: '3.5'
services:
  mysql:
    image: mysql
    container_name: phoros_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: phoros_db
      MYSQL_USER: crafterZos
      MYSQL_ROOT_PASSWORD: crafterZos
      MYSQL_PASSWORD: crafterZos
    ports:
      - 3306:3306
    volumes:
      - 'phoros_db:/crafterZos/phoros/data'
volumes:
  phoros_db:
    driver: local